
// ==========================================
// Shared Data Constants
// ==========================================

export const BRAND_OPTIONS = [
    { value: "Hikvision", label: "Hikvision" },
    { value: "Dahua", label: "Dahua" },
    { value: "Uniview (UNV)", label: "Uniview (UNV)" },
    { value: "Watashi", label: "Watashi" },
    { value: "Hi-View", label: "Hi-View" },
    { value: "People Fu", label: "People Fu" },
    { value: "Fujiko", label: "Fujiko" },
    { value: "Kenpro", label: "Kenpro" },
    { value: "Ezviz", label: "Ezviz" },
    { value: "Imou", label: "Imou" },
    { value: "Vstarcam", label: "Vstarcam" },
    { value: "TP-Link", label: "TP-Link" },
    { value: "Xiaomi", label: "Xiaomi" },
    { value: "Axis Communications", label: "Axis Communications" },
    { value: "Bosch", label: "Bosch" },
    { value: "Panasonic (i-PRO)", label: "Panasonic (i-PRO)" },
    { value: "Honeywell", label: "Honeywell" },
    { value: "Avigilon", label: "Avigilon" },
    { value: "Pelco", label: "Pelco" },
    { value: "Hanwha Vision", label: "Hanwha Vision" },
    { value: "Tiandy", label: "Tiandy" },
    { value: "Milesight", label: "Milesight" },
    { value: "Pixel", label: "Pixel" },
    { value: "Vigilant", label: "Vigilant" },
    { value: "Hilook", label: "Hilook" },
    { value: "Reolink", label: "Reolink" },
    { value: "Ring", label: "Ring" },
    { value: "Arlo", label: "Arlo" },
    { value: "Anker Eufy", label: "Anker Eufy" },
    { value: "Cisco", label: "Cisco" },
    { value: "Cisco Meraki", label: "Cisco Meraki" },
    { value: "HPE Aruba Networking", label: "HPE Aruba Networking" },
    { value: "Juniper Networks", label: "Juniper Networks" },
    { value: "Fortinet", label: "Fortinet" },
    { value: "Palo Alto Networks", label: "Palo Alto Networks" },
    { value: "Check Point", label: "Check Point" },
    { value: "Sophos", label: "Sophos" },
    { value: "SonicWall", label: "SonicWall" },
    { value: "WatchGuard", label: "WatchGuard" },
    { value: "Sangfor", label: "Sangfor" },
    { value: "H3C", label: "H3C" },
    { value: "Huawei", label: "Huawei" },
    { value: "ZTE", label: "ZTE" },
    { value: "Ruijie Networks", label: "Ruijie Networks" },
    { value: "Reyee", label: "Reyee" },
    { value: "Ubiquiti (UniFi)", label: "Ubiquiti (UniFi)" },
    { value: "MikroTik", label: "MikroTik" },
    { value: "Cambium Networks", label: "Cambium Networks" },
    { value: "Ruckus Networks (CommScope)", label: "Ruckus Networks (CommScope)" },
    { value: "Engenius", label: "Engenius" },
    { value: "Allied Telesis", label: "Allied Telesis" },
    { value: "Alcatel-Lucent Enterprise", label: "Alcatel-Lucent Enterprise" },
    { value: "Arista Networks", label: "Arista Networks" },
    { value: "Extreme Networks", label: "Extreme Networks" },
    { value: "Dell Technologies", label: "Dell Technologies" },
    { value: "D-Link", label: "D-Link" },
    { value: "Zyxel", label: "Zyxel" },
    { value: "Netgear", label: "Netgear" },
    { value: "Linksys", label: "Linksys" },
    { value: "Asus", label: "Asus" },
    { value: "Tenda", label: "Tenda" },
    { value: "Mercusys", label: "Mercusys" },
    { value: "Totolink", label: "Totolink" },
    { value: "Edimax", label: "Edimax" },
    { value: "Synology", label: "Synology" },
    { value: "QNAP", label: "QNAP" },
    { value: "DrayTek", label: "DrayTek" },
    { value: "Peplink", label: "Peplink" },
    { value: "Teltonika Networks", label: "Teltonika Networks" },
    { value: "Moxa", label: "Moxa" },
    { value: "Advantech", label: "Advantech" },
    { value: "Planet", label: "Planet" },
    { value: "LevelOne", label: "LevelOne" },
    { value: "Volktek", label: "Volktek" },
    { value: "Brocade", label: "Brocade" },
    { value: "F5 Networks", label: "F5 Networks" },
    { value: "Radware", label: "Radware" },
    { value: "A10 Networks", label: "A10 Networks" },
    { value: "Barracuda Networks", label: "Barracuda Networks" },
    { value: "Riverbed", label: "Riverbed" },
    { value: "Cradlepoint", label: "Cradlepoint" },
    { value: "Grandstream", label: "Grandstream" },
    { value: "Yealink", label: "Yealink" },
    { value: "Fanvil", label: "Fanvil" },
    { value: "Gigaset", label: "Gigaset" },
    { value: "Poly (Polycom)", label: "Poly (Polycom)" },
    { value: "Avaya", label: "Avaya" },
    { value: "Snom", label: "Snom" },
    { value: "Alcadon", label: "Alcadon" },
    { value: "Panduit", label: "Panduit" },
    { value: "Link (Cabling)", label: "Link (Cabling)" },
    { value: "Interlink", label: "Interlink" },
    { value: "AMP (CommScope)", label: "AMP (CommScope)" },
    { value: "Belden", label: "Belden" },
    { value: "Furukawa", label: "Furukawa" },
    { value: "Haco", label: "Haco" },
    { value: "Other", label: "Other..." }
];

export const DISTRIBUTOR_OPTIONS = [
    { value: "A Z KING", label: "บริษัท เอเซ็ดคิง จำกัด" },
    { value: "Chai Solution", label: "บริษัท ชัย โซลูชั่น จำกัด" },
    { value: "Comtelsat", label: "บริษัท คอมเทลแซท จำกัด" },
    { value: "DGF", label: "บริษัท ดิจิตอล โฟกัส จำกัด" },
    { value: "Digital Com", label: "บริษัท ดิจิตอลคอม จำกัด" },
    { value: "DT Tele Data", label: "บริษัท ดีทีเทเลดาต้า เทคโนโลยี" },
    { value: "Easy Network", label: "บริษัท อีซี่ เน็ต จำกัด" },
    { value: "HD Digital CCTV", label: "บริษัท เอชดี.ดิจิตอล.ซีซีทีวี จำกัด" },
    { value: "HIP", label: "บริษัท เอช ไอ พี โกลบอล จำกัด" },
    { value: "Inter Link", label: "บริษัท อินเตอร์ลิ้งค์ คอมมิวนิเคชั่น จำกัด (มหาชน)" },
    { value: "KST", label: "บริษัท เค.เอส.ที.ซิสเต็ม จำกัด" },
    { value: "Lazada", label: "บริษัท ลาซาด้า จำกัด" },
    { value: "NP Tech Solution", label: "ห้างหุ้นส่วนจำกัด เอ็นพี เทค โซลูชั่น" },
    { value: "NVK", label: "บริษัท เอ็น.วี.เค.อินเตอร์ จำกัด" },
    { value: "Renew Sale", label: "บริษัท รีนิว เทคโนโลยี จำกัด" },
    { value: "Richwave", label: "บริษัท ริชเวฟ คอมมูนิเคชั่น จำกัด" },
    { value: "Samcom SMC", label: "บริษัท ซัมคอม เทคโนโลยี จำกัด" },
    { value: "SEC Stock", label: "บริษัท เอสอีซี เทคโนโลยี จำกัด" },
    { value: "Shopee", label: "บริษัท ช้อปปี้ (ประเทศไทย) จำกัด" },
    { value: "SiS", label: "บริษัท เอสไอเอส ดิสทริบิวชั่น (ประเทศไทย) จำกัด (มหาชน)" },
    { value: "Syndome", label: "บริษัท ซินโดม อิเลคทรอนิคส์ อินดัสตรี จำกัด" },
    { value: "Synnex", label: "บริษัท ซินเน็ค (ประเทศไทย) จำกัด (มหาชน)" },
    { value: "TAI SIN NETCAM", label: "บริษัท ไท ซิน เนทแคม จำกัด" },
    { value: "TCT", label: "บริษัท ทีซีที วาตาชิ กรุ๊ป จํากัด" },
    { value: "TMV Inter Trading", label: "บริษัท ทีเอ็มวี อินเตอร์ เทรดดิ้ง จำกัด" },
    { value: "USupply", label: "บริษัท ยู.ซัพพลาย แอนด์ คอมมูนิเคชั่น จำกัด" },
    { value: "VST-ECS", label: "บริษัท วีเอสที อีซีเอส (ประเทศไทย) จำกัด" },
    { value: "ZK Teco", label: "บริษัท เบนเนกซ์ จำกัด" },
    { value: "Other", label: "Other..." } 
];

export const COMMON_ACCESSORIES = [
    "acc_box", "acc_adapter", "acc_hdmi", "acc_mouse", "acc_remote", "acc_hdd", "acc_cables"
];
